#!/usr/bin/bash

#screenshot 
grim ~/.config/hypr/lock.png 

#blur
convert -scale 20% -blur 0x1 -resize 500% ~/.config/hypr/lock.png ~/.config/swaylock/lockscreen.png

#delete the screenshot

rm ~/.config/hypr/lock.png

swaylock -f
