theme = "trans"

[editor]
completion-trigger-len = 1
idle-timeout = 0
mouse = false
# bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
x = ["goto_line_start", "select_mode", "goto_line_end_newline"]

[keys.insert]
C-space = "signature_help"
